In [1]:
langs = []
langs.append("Python")
langs.append("Perl")
print(langs)

['Python', 'Perl']


In [2]:
langs.insert(0, "PHP")
langs.insert(2, "Lua")
print(langs)

['PHP', 'Python', 'Lua', 'Perl']


In [3]:
langs.extend(("Javascript", "Actionscript"))
print(langs)

['PHP', 'Python', 'Lua', 'Perl', 'Javascript', 'Actionscript']


In [4]:
del langs[1]
print(langs)

['PHP', 'Lua', 'Perl', 'Javascript', 'Actionscript']


In [5]:
del langs[:]
print(langs)

[]


In [6]:
dict = {'Name':'Azra', 'Age':1, 'Class':'First'}
print("dict['Name']: ", dict['Name'])
print("dict['Age']: ", dict['Age'])

dict['Name']:  Azra
dict['Age']:  1


In [7]:
dict = {'Name':'Azra', 'Age':1, 'Class':'First'}
dict['Age'] = 8
dict['School'] = 'Primary School'

In [8]:
print("dict['Age']: ", dict['Age'])
print("dict['School']: ", dict['School'])

dict['Age']:  8
dict['School']:  Primary School


In [9]:
dict = {'Name':'Azra', 'Age':1, 'Name': 'Ayşe'}
print("dict['Name']: ", dict['Name'])

dict['Name']:  Ayşe


In [10]:
dict = {'Name':'Azra', 'Age':1, 'Class':'First'}
del dict['Name']

In [11]:
print("dict['Name']: ", dict['Name'])

KeyError: 'Name'

In [12]:
dict.clear()

In [13]:
print("dict['Age']: ", dict['Age'])

KeyError: 'Age'

In [14]:
del dict

In [15]:
phonebook = {'Chris':'555-1111', 'Katie':'555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [16]:
phonebook = {'Chris':'555-1111', 'Katie':'555-2222', 'Joanne':'555-3333'}
for key, value in phonebook.items():
    print(key, value)

Chris 555-1111
Katie 555-2222
Joanne 555-3333


In [17]:
#Lambda, Filter, Map, Reduce
"""
lambda num1, num2 : num1 + num2
filter, map, reduce (function, iterable)
"""

'\nlambda num1, num2 : num1 + num2\nfilter, map, reduce (function, iterable)\n'

In [18]:
addition = lambda a : a + 10
print(addition(5))

15


In [19]:
product = lambda a, b : a * b
print(product(5, 6))

30


In [20]:
addition = lambda a, b, c : a + b + c
print(addition(5, 6, 2))

13


In [21]:
#def myfunction(positional arguments, *args, named arguments, **kwargs)
#def myfunction(10, b = 20)

In [22]:
res = (lambda *args : sum(args))
res(10, 20), res(10,20,30,40), res(10,20,30,40,50,60,70)

(30, 100, 280)

In [24]:
res1 = (lambda **kwargs : sum(kwargs.values()))
print(res1(a = 10, b = 20, c = 30), res1(a = 10, b = 20, c = 30, d = 40, e = 50))

60 150


In [25]:
def product(nums):
    total = 1
    for i in nums:
        total *= i
    return total

res1 = (lambda **kwargs : product(kwargs.values()))
res1(a = 10, b = 20, c = 30), res1(a = 10, b = 20, c = 30, d = 40, e = 50)

(6000, 12000000)

In [26]:
list1 = [1,2,3,4,5,6,7,8,9]

def odd(n):
    if n%2 == 1:
        return True
    else:
        return False
    
odd_num = list(filter(odd, list1))
odd_num

[1, 3, 5, 7, 9]

In [27]:
list1 = [1,2,3,4,5,6,7,8,9]
odd_num = list(filter(lambda n : n%2 == 1, list1))
odd_num

[1, 3, 5, 7, 9]

In [28]:
def twice(n):
    return n*2

doubles = list(map(twice, odd_num))
doubles

[2, 6, 10, 14, 18]

In [29]:
doubles = list(map(lambda n : n*2, odd_num))
doubles

[2, 6, 10, 14, 18]

In [30]:
from functools import reduce

def add(a, b):
    return a + b

sum_all = reduce(add, doubles)
sum_all

50

In [31]:
sum_all = reduce(lambda a,b : a+b, doubles)
sum_all

50

In [34]:
list5 = [i for i in range(10) if i%2==1]
sum_all = reduce(lambda a,b : a+b, list(map(lambda n : n*2, list(filter(lambda n : n%2 == 1, list5)))))
sum_all

50

In [35]:
from numpy import *
import time

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

trad_version()

4.898905992507935

In [36]:
def numpy_version():
    t1 = time.time()
    X = arange(10000000)
    Y = arange(10000000)
    Z = X + Y
    return time.time() - t1

numpy_version()

0.05980324745178223

In [37]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [38]:
mylist1 = [10,20,30,40,50,60]
mylist1

[10, 20, 30, 40, 50, 60]

In [39]:
type(mylist1)

list

In [40]:
arr1 = np.array(mylist1)
arr1

array([10, 20, 30, 40, 50, 60])

In [41]:
type(arr1)

numpy.ndarray

In [42]:
arr1.data

In [43]:
arr1.dtype

dtype('int32')

In [44]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [45]:
#arange
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [48]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [49]:
arr3.size

10

In [50]:
arr3.dtype

dtype('int32')

In [51]:
arr3.itemsize

4

In [52]:
arr3.nbytes

40

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [56]:
a = np.array([10, 20 ,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [57]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [58]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [61]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [62]:
np.random.random(4)

array([0.61960711, 0.51430965, 0.40231429, 0.47759074])

In [63]:
np.random.randint(0, 500, 5)

array([418, 318,  88, 290, 345])

In [64]:
np.random.randint(0, 500, 10)

array([379, 245, 451, 213, 348, 481, 229, 240,  72,  43])

In [65]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [66]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [67]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [68]:
f1 = np.random.uniform(5, 10, size = 10)
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [69]:
np.random.seed(99)
np.random.randint(0, 100, 10)

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1])

In [70]:
np.random.seed(99)
np.random.randint(0, 100, 10)

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1])