In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
f1 = np.random.uniform(5, 10, size=(10))
f1

array([6.05964381, 9.90052678, 7.89595888, 7.65896623, 5.77316702,
       7.50859869, 6.49309524, 5.89523943, 9.2604305 , 6.65417905])

In [3]:
np.floor(f1)

array([6., 9., 7., 7., 5., 7., 6., 5., 9., 6.])

In [4]:
f1.astype(int)

array([6, 9, 7, 7, 5, 7, 6, 5, 9, 6])

In [6]:
b2 = np.random.randn(10)
b2

array([-0.30994766,  1.03789293,  0.07702   , -0.33766562, -0.41785985,
       -0.23998956,  0.29627553, -1.09603382,  0.2442981 , -0.44892579])

In [7]:
mylist1 = [10,20,30,40,50,60]
arr1 = np.array(mylist1)
arr1

array([10, 20, 30, 40, 50, 60])

In [8]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [9]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
arr2.sum()

190

In [11]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [ ]:
#min(), max(), argmin(), argmax(), mean(), median(), var()

In [12]:
np.std(arr2)

5.477225575051661

In [13]:
A = np.array([[1,2,3,0], [5,6,7,22], [10, 11, 1, 13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [14]:
A.sum()

129

In [ ]:
#min(), max(), mean(), median(), var(), std()

In [15]:
np.amin(A, axis = 0) #sütun bazlı sıralama

array([1, 2, 1, 0])

In [16]:
np.amin(A, axis = 1) #satır bazlı sıralama

array([0, 5, 1, 3])

In [17]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [18]:
a = np.array([7,5,3,9,0,2])

In [19]:
a[0]

7

In [20]:
a[1:]

array([5, 3, 9, 0, 2])

In [21]:
a[-1]

2

In [24]:
a[-4:-2]

array([3, 9])

In [25]:
#Elemanları değiştirme
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [27]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [29]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [30]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [32]:
#Eksik Değerler (Missing Values)

In [33]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [34]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [35]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [36]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [37]:
A = np.array([[1,2,np.nan,4],[np.nan,6,7,8],[10,np.nan,12,13],[14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [38]:
np.isnan(A) #eleman nan mı değil mi kontrolü

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [39]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [40]:
#Dizilerin birleştirilmesi
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
a99 = np.zeros(64).reshape(8, 8)
a99

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
np.vstack([a,b]) #Dikey ekleme

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.hstack([a,b]) #Yatay ekleme

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [46]:
#Ortak elemanları bulma

In [47]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [48]:
np.intersect1d(c1, c2)

array([20, 40, 60])

In [49]:
np.setdiff1d(c1, c2)

array([10, 30, 50])

In [50]:
a1 = np.arange(0, 60)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [51]:
a1[np.where ((a1 > 20) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [52]:
a1[np.where (((a1 > 20) & (a1 < 35)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [53]:
a1[np.where(np.logical_and(a1 > 20, a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [54]:
#Dizinin tersini alma
a4 = np.arange(10, 30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [55]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [56]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [57]:
a3 = np.array([[3,2,8,1],[70,50,10,67],[45,25,75,15],[12,9,77,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [58]:
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [59]:
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [60]:
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [61]:
#Sıralama
a = np.array([10,5,2,22,12,92,17,33])
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [62]:
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [64]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [65]:
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [66]:
np.sort(a3, axis = 1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [67]:
np.sort(a3, axis = 0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [68]:
b = np.sort(a)
b = b[::-1]
b

array([92, 33, 22, 17, 12, 10,  5,  2])

In [69]:
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

In [70]:
a[::-1].sort()
a

array([92, 33, 22, 17, 12, 10,  5,  2])

In [72]:
p4 = np.loadtxt('data/sample.txt', dtype = np.integer)
p4

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [74]:
p5 = np.genfromtxt('data/sample0.txt', dtype = 'str')
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')

In [75]:
p5[0]

array(['Dogu', 'Turkey', 'Football'], dtype='<U10')

In [76]:
p5[:,0]

array(['Dogu', 'John', 'Paul'], dtype='<U10')

In [77]:
np.loadtxt('data/sample.txt', delimiter=' ', usecols = (0,2))

array([[24., 88.],
       [ 1.,  8.],
       [33., 99.],
       [39., 98.],
       [22., 87.]])

In [78]:
p7 = np.arange(10, 200, 11)
p7

array([ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109, 120, 131, 142,
       153, 164, 175, 186, 197])

In [79]:
np.savetxt('test3.csv', p7, delimiter = ',')

In [80]:
p8 = np.arange(0, 121).reshape(11,11)

In [81]:
p8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [82]:
np.save('test4.npy', p8)

In [83]:
p9 = np.load('test4.npy')
p9

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [84]:
np.save('numpyfile', p8)

In [85]:
p10 = np.load('numpyfile.npy')
p10

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])